version: '3.9'
services:
  web:
    image: tsoutello/rest-service:1.0.0
    ports:
      - "9797:80"
    tty: true
    stdin_open: true
    deploy:
      resources:
        limits:
          memory: 768M
