---
kind: Namespace
apiVersion: v1
metadata:
  name: spring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-service
  namespace: rest-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-service
  template:
    metadata:
      labels:
        app: rest-service
    spec:
      containers:
      - image: tsoutello/spring-backend:1.0.4
        name: rest-service
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
              path: /rest-service/api/actuator/health/livenessState
              port: 80
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
              path: /rest-service/api/actuator/health/readinessState
              port: 80
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
          successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: rest-service
  namespace: rest-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: rest-service