---
kind: Namespace
apiVersion: v1
metadata:
  name: spring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spring
  name: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - image: tsoutello/spring-backend:1.0.1
        name: spring-backend
        ports:
          - containerPort: 9797
---
apiVersion: v1
kind: Service
metadata:
  name: spring
  namespace: spring
  labels:
    app: spring
spec:
  type: LoadBalancer
  ports:
  - port: 9797
    protocol: TCP
    targetPort: 9797
  selector:
    app: spring
